### ISSUE TITLE
How to access a csscomb.json file

### ISSUE THREAD

**Issue by akileez** [bassjobsen/less-plugin-csscomb#1]
How do I use a personal csscomb config file instead of the baked in defaults?
tried doing this and a bunch of other ways...

```
lessc assets/styles/less/main.less --csscomb="./.csscomb.json"
```

**Comment by bassjobsen** [comment]
thanks s for posting your issue. It should work now. Set the path to your config as an argument for the plugin: `lessc test.less --csscomb="config/test.json"`

**Comment by akileez** [comment]
beautiful!!! thanks.

**Comment by wolfy1339** [comment]
Is this the same for using it in a Gulp task?
